config/routes.rb
Rails.application.routes.draw do
  

  resources :sites

  get 'galleries/top'
  get 'galleries/random'
  get 'stylists/top'
  get 'stylists/random'

  resources :comments

  devise_for :users
  
  resources :users do
    resources :activities
    member do
      put "follow", to: "users#follow"
      put "unfollow", to: "users#unfollow"
      get "feed", to: "users#feed"
      get "interaction", to: "users#interaction"
    end
  end
   
  resources :styles do
    resources :comments
    member do
      put "like", to: "styles#vote"
      put "unlike", to: "styles#unvote"
    end
  end
  

  get 'pages/about'
  get 'pages/weekly'
  get 'pages/monthly'
  get 'pages/contact'
  get 'pages/show'
  get 'pages/gallery'
  get 'pages/form'
  get 'pages/contest'
  
  root 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :posts, class_name: "Style", foreign_key: "user_id"
  has_many :styles, class_name: "Style", foreign_key: "stylist_id"
  has_many :comments, dependent: :destroy
  has_many :activities
  validates :name, :phone, :presence => true 
  
  acts_as_voter
  acts_as_follower
  acts_as_followable
  
  mount_uploader :image, ImageUploader
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:follow, :unfollow, :feed]
   before_filter :authenticate_user!, only: [:follow, :unfollow]
  def show
     @user = User.find(params[:id])

    respond_to do |format|
        format.html # show.html.erb
        format.xml { render :xml => @user }
    end
  end
  
  def feed
    @followers=@user.followers
    
    @styles= Style.where(user: @followers).take(30)
  end
  
  def interaction
    @activities = Activity.where(actor_id: @user.id)
  end


 
  def follow
    current_user.follow(@user)
    redirect_to @user
    activity= Activity.create(params[:activity])
    activity.actor_id = current_user.id
    activity.action = " followed "
    activity.receiver_id= @user.id
    activity.action_type= "follow"
    activity.save
  end
  
  def unfollow
    current_user.stop_following(@user)
    redirect_to @user

  end
  
 private
    # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/feed.html.erb
    <section class="colon14">
      <% if @user == current_user %>
        <% @name="My Hair Feed" %>       
      <% else %>
      <% @name= @user.name + "'s Hair Feed" %>      
      <% end %>

      
      
        <!-- START CONTENT AND SIDEBAR -->
        <div class="container general">
            <div id="content" class="single col-lg-12 col-md-12 col-sm-12">

                <div class="message text-center">
                  <h2><span><%= @user.name %>'s</span> hair feed</h2>
                </div>
          
     
<ul>
         
  


<% @styles.each do |style| %>    
                <div class="col-lg-3 col-md-3 col-sm-6">
                	<div class="portfolio-columns">
                    <%= link_to(style,  "data-no-turbolink" => true) do %>                  
                      <%= cl_image_tag(style.image1,  :x => style.crop_x, :y => style.crop_y, :width => 250, :height => 250, :crop => :fill) %>
                    <div>
                      <br><br>
                    <h5><%= style.name %></h5>
                    </div>
                    <%end %>
                   </div>
                </div>
    <% end %>       
              

  
    <!-- END CONTENT -->
    
	</section><!-- end colon1 -->

app/views/users/interaction.html.erb
    <section class="colon14">
      <% if @user == current_user %>
        <% @name="My Hair Feed" %>       
      <% else %>
      <% @name= @user.name + "'s Hair Feed" %>      
      <% end %>


        <!-- START CONTENT AND SIDEBAR -->
        <div class="container general">
            <div id="content" class="single col-lg-12 col-md-12 col-sm-12">

                <div class="message text-center">
                  <h2><span><%= @user.name %>'s</span> Activity feed</h2>
                </div>
          
     
<ul>
         
  



    <% @activities.each do |activity| %>
        <% if activity.action_type == "comment" %>
          
  <p><%= link_to image_tag(@user.image.url(:thumbnail), width: '50'), @user %> <%= link_to @user.name, @user %> commented "<%= activity.content %>" on <%= link_to image_tag(User.find_by(id: activity.receiver_id).image.url(:thumbnail), width: '50'), User.find_by(id: activity.receiver_id) %> <%= link_to User.find_by(id: activity.receiver_id).name, User.find_by(id: activity.receiver_id) %>'s <%= link_to "post", Style.find_by(id: activity.object_id) %></p>
  
        <% elsif activity.action_type == "like" %>
            <p><%= link_to @user.name, @user %> liked <%= link_to User.find_by(id: activity.receiver_id).name, User.find_by(id: activity.receiver_id) %>'s <%= link_to "post", Style.find_by(id: activity.object_id) %></p>
    
        <% elsif activity.action_type == "follow" %>
             <p> <%= link_to @user.name, @user %> <%= activity.action %> <%= link_to User.find_by(id: activity.receiver_id).name, User.find_by(id: activity.receiver_id) %> </p>
        <% end %>

      
    <% end %>
   </ul>
              
 

        </div><!-- end container -->
         
  
    <!-- END CONTENT -->
    
	</section><!-- end colon1 -->

app/views/users/show.html.erb
<section class="colon14">
  <% @name= @user.name%>
       
        <!-- START CONTENT AND SIDEBAR -->
        <div class="container general buddypress-container">
        
            <div id="content" class="single col-lg-8 col-md-8 col-sm-12">

                <div class="buddypress-single-header">
                	<div class="col-lg-3 col-md-3 col-sm-12">
						<div class="buddy-group-blocks buddy-members">
							<figure class="inverse">
                <%if @user.image? %>
                 <%= cl_image_tag(@user.image.url(:thumbnail)) %>
               <%else %>
                  <%= image_tag("http://res.cloudinary.com/bisonshare/image/upload/v1426705998/https_www.leanstartupmachine.com_images_default_profile_photo_hjtmyk.png") %>
               <%end %>
                <hr>
                <% if (user_signed_in?) && (current_user != @user) %>
                  <% if current_user.following?(@user)%>
                     <%= link_to "Following", unfollow_user_path(@user), method: :put, class:"btn btn-primary btn-block text-center" %>
                   <% else %>
                      <%= link_to "Follow", follow_user_path(@user), method: :put, class:"btn btn-default btn-block text-center" %>
                   <% end %>
                <% elsif  current_user != @user %>
                   <%= link_to "Follow", follow_user_path(@user), method: :put, class:"btn btn-default btn-block text-center" %>
                <% end %>
                  
                
						</div>
                    </div>
                    
                	<div class="col-lg-9 col-md-9 col-sm-12">
							<figcaption>
                <h3><%= @user.name %></h3>
                
                <p><%= @user.bio %></p>
                
                
							</figcaption>
							</figure>
                    </div>
                </div> <!-- end author -->
               
              <div class="clearfix"></div>
              <div class="divider"></div>

              <div class="col-sm-12 col-lg-12">
                <div class="well">
                	<ul>
                    	<li><h5>Followers<span class="label label-warning" data-effect="pop"> <%= @user.followers.count %></span>
                   Following <span class="label label-warning" data-effect="pop"><%= @user.follows.count %></span></h5></li>
                    <li><h5>Posted<span class="label label-warning" data-effect="pop"><%= @user.styles.count %> </span>styles</h5></li>
                    <li><h5><%= link_to "View their Feed", feed_user_path(@user), method: :get %></h5></li>
                    </ul>
              <div class="clearfix"></div>
                </div>
              </div>

                
<ul class="buddy-activity">

				<li>
          <h3 class="text-center"> Styles shared by <%= @user.name %></h3>
          <% @user.styles.each do |style| %>    
                    <div class="col-lg-3 col-md-3 col-sm-6">
                      <div class="portfolio-columns">
                        <%= link_to(style,  "data-no-turbolink" => true) do %>                  
                          <%= cl_image_tag(style.image1,  :x => style.crop_x, :y => style.crop_y, :width => style.crop_w, :height => style.crop_h, :crop => :crop) %>
                        <div>
                          <br><br>
                        <h5><%= style.name %></h5>
                        </div>
                        <%end %>
                       </div>
                    </div>
            <% end %>       
				</li>
  
  </ul>
              <hr>
              
<ul class="buddy-activity">
  		<li>
          <h3 class="text-center"> Styles done by <%= @user.name %></h3>
        <% @user.posts.each do |style| %>    
                    <div class="col-lg-3 col-md-3 col-sm-6">
                      <div class="portfolio-columns">
                        <%= link_to(style,  "data-no-turbolink" => true) do %>                  
                          <%= cl_image_tag(style.image1,  :x => style.crop_x, :y => style.crop_y, :width => style.crop_w, :height => style.crop_h, :crop => :crop) %>
                        <div>
                          <br><br>
                        <h5><%= style.name %></h5>
                        </div>
                        <%end %>
                       </div>
                    </div>
            <% end %>       
				</li>

		
			</ul>

                      
    		<div class="clearfix"></div>
            
            </div><!-- end content -->
            
            
            <div id="sidebar" class="col-lg-4 col-md-4 col-sm-12">
				
                <div class="widget">
                    <div class="search">
                        <input type="text" size="16" placeholder="Search&hellip;" name="s" id="s">
                    </div>
                </div>
                                
                <div class="widget">
            	<h2 class="general-title">
                <span>Styles <%= @user.name %> likes</span>
				</h2>
                	<div class="buddy-members">
                    <ul>
                      <li>  <% @user.find_voted_items.take(10).each do |style| %> 
                               
                                  <%= link_to cl_image_tag(style.image1), style %>
                              
                            <% end %></li>
                    
                      
                   </ul>
                    </div>
                </div>

				<div class="clearfix"></div>
                

                
                
            </div><!-- end sidebar -->
            
        </div><!-- end container -->
	
    <!-- END CONTENT AND SIDEBAR -->
    
	</section><!-- end colon1 -->