config/routes.rb
Rails.application.routes.draw do
  

  resources :sites

  get 'galleries/top'
  get 'galleries/random'
  get 'stylists/top'
  get 'stylists/random'

  resources :comments

  devise_for :users
  
  resources :users do
    resources :activities
    member do
      put "follow", to: "users#follow"
      put "unfollow", to: "users#unfollow"
      get "feed", to: "users#feed"
      get "interaction", to: "users#interaction"
    end
  end
   
  resources :styles do
    resources :comments
    member do
      put "like", to: "styles#vote"
      put "unlike", to: "styles#unvote"
    end
  end
  

  get 'pages/about'
  get 'pages/weekly'
  get 'pages/monthly'
  get 'pages/contact'
  get 'pages/show'
  get 'pages/gallery'
  get 'pages/form'
  get 'pages/contest'
  
  root 'pages#home'

end

app/models/style.rb
class Style < ActiveRecord::Base
  
  acts_as_votable
  #acts_as_mappable :auto_geocode=>true
  
  validates :name, :description, :presence => true
  mount_uploader :image1, ImageUploader
  
  belongs_to :user
  belongs_to :stylist, class_name: "User"
  
  has_many :comments, dependent: :destroy
  has_many :activities

#this is changing
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: [:show, :edit, :update, :destroy, :vote, :unvote]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :vote]
  before_filter :check_user, only: [:edit, :update, :destroy]
  # GET /styles
  # GET /styles.json
  def index
    @styles = Style.paginate(:page => params[:page], :per_page => 12).order('created_at DESC')
  end

  # GET /styles/1
  # GET /styles/1.json
  def show
  end
  
  def vote
    @style.liked_by current_user
    @style.total_votes = @style.votes_for.size
    redirect_to @style
    activity= Activity.create(params[:activity])
    activity.actor_id = current_user.id
    activity.action = " liked a post from "
    activity.object_id= @style.id
    activity.receiver_id= @style.user.id
    activity.action_type="like"
    activity.save
  end
  
  def unvote
    @style.unliked_by current_user
    @style.total_votes=@style.votes_for.size
    redirect_to @style
  end

  # GET /styles/new
  def new
    @style = Style.new
  end

  # GET /styles/1/edit
  def edit
  end

  # POST /styles
  # POST /styles.json
  def create
    @style = Style.new(style_params)
    @style.user_id= current_user.id
    @style.total_votes= 0
    @style.position = request.remote_addr 
    respond_to do |format|
      if @style.save 
        #format.html { redirect_to @style, notice: 'Style was successfully created.' }
        #format.json { render :show, status: :created, location: @style }
          format.html { render :action => 'crop' }
      else
        format.html { render :new }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /styles/1
  # PATCH/PUT /styles/1.json
  def update
    respond_to do |format|
   
      if @style.update(style_params) && (@style.tag==true)
        format.html { render :action => 'crop' }
        
      elsif @style.update(style_params)
         format.html { redirect_to @style, notice: 'Style was successfully updated.' }
        format.json { render :show, status: :ok, location: @style }
      else
        format.html { render :edit }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1
  # DELETE /styles/1.json
  def destroy
    @style.destroy
    respond_to do |format|
      format.html { redirect_to styles_url, notice: 'Style was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_style
      @style = Style.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def style_params
      params.require(:style).permit(:name, :description, :image1, :image2, :image3, :image4, :poster_id, :stylist_id, :crop_x, :crop_y, :crop_h, :crop_w, :total_votes, :phone, :stylist_name, :tag, :position)
    end
  
   def check_user
     if current_user != @style.user
       redirect_to root_url, alert: "Sorry, this Style belongs to someone else"\
      end
  end

end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.erb
<section class="colon14">
  
  <% @style.update_attributes(:tag => true) %>     
  
<%= form_for(@style, :html => {:class => 'register-form'}) do |f| %>
  <% if @style.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@style.errors.count, "error") %> prohibited this style from being saved:</h4>

      <ul>
      <% @style.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

        <!-- START CONTENT AND SIDEBAR -->
        <div class="container general">
        
            <div id="content" class="single col-lg-10 col-md-10 col-sm-10">

			<div class="clearfix"></div>
           
            
              <div class="col-sm-12 col-lg-10 col-lg-offset-3">
                <p class="lead text-muted"><%= @name %></p>
                <form class="form-horizontal">
                  <div class="form-group">
                    <div class="col-lg-10">
  
                     <div class="form-group"> 
                       <%= f.text_field :name, class:'form-control', placeholder: 'Name', required: true %>
                      </div>
                      <div class="form-group">
                        <%= f.text_area :description, class:'form-control', placeholder: 'Description', required: true %>
                       </div>
                      <div class="form-group">
                        <%= f.text_field :phone, class:'form-control', placeholder: 'Enter the phone number of the hair stylist', required: true %>
                       </div>
                      <div class="form-group">
                        
                      </div>
                      <div class="form-group">
                        
                        <%= f.file_field :image1, class:'form-control', placeholder: 'Title' %>
                       </div>
                      <% if @name =="Editing style" %>  
                      <div class="form-group">
                        <% f.label "Would you like to crop the image?" %>
                        <%= f.select :tag, [["Yes", "true"], ["No", "false"]] , class: "form-control"  %>
                      </div> 
                      <% end %>  
                      <%= f.submit "Continue", class:"btn btn-primary" %>
                      
                      <br>
                      <%= link_to 'Back', styles_path %>
                    </div>
                  </div>
                  
                </form>          
              </div>

			<div class="clearfix"></div>
            
            
            

            </div><!-- end content -->
            
        </div><!-- end container -->
	
    <!-- END CONTENT AND SIDEBAR -->
  <% end %>
  
	</section><!-- end colon1 -->

app/views/styles/crop.html.erb
<% @name= "Cropping " + @style.name %>
<% @style.update_attributes(:tag => false) %>  
    <section class="colon14">
        <!-- START CONTENT AND SIDEBAR -->
        <div class="container general">
            <div id="content" class="single col-lg-12 col-md-12 col-sm-12 text-center">
             <%= form_for @style do |f| %>
              <h2>Tagging the Stylist</h2>
              <br>
              <h4>Select your stylist from this list (if found)</h4>
              
              
             <div class="row">
                    <div class="col-md-12">
                      
                      <%User.where(phone: @style.phone).each do |user| %>
                      <%= f.select :stylist_id, [[user.name, user.id]] , :prompt => 'Select a Stylist', class:"form-control", required: "true", class: "form-control"  %>
                          <% end %>
                    </div>
             </div>
                
                
              <h4>and Enter the Stylist's name</h4>
               
                  <div class="row">
                        <div class="col-md-4  col-md-offset-4"> 
                          <%= f.text_field :stylist_name, class: "form-control"  , required: "true"%>
                        </div>
                        
                  </div>
              <br><br>
              <h2>Cropping The Image</h2>
             
              <%= image_tag @style.image1.url, :id => "cropbox" %>

              
                <%= f.hidden_field :crop_x, :id => "crop_x" %>
                <%= f.hidden_field :crop_y, :id => "crop_y" %>
                <%= f.hidden_field :crop_h, :id => "crop_h" %>
                <%= f.hidden_field :crop_w, :id => "crop_w" %>
              <br>
              <p><%= f.submit "Submit the style!", class:"btn btn-primary btn-lg"%>
              
              
         
              
              </p>
              <% end %>
              
             
        </div>  	
    <!-- END CONTENT -->
      </div>
	</section><!-- end colon1 -->


<script type="text/javascript">

  
  $(function() {
  $('#cropbox').Jcrop({
    onChange: update_crop,
    onSelect: update_crop,
    setSelect: [0, 0, 500, 500],
    aspectRatio: 1
  });
});
  
  function update_crop(coords) {
  $('#crop_x').val(coords.x);
  $('#crop_y').val(coords.y);
  $('#crop_w').val(coords.w);
  $('#crop_h').val(coords.h);  
}
</script>

app/views/styles/edit.html.erb
<% @pages="new" %>
<% @name ="Edit Style" %>
<%= render 'form' %>

<%= link_to 'Show', @style %> |
<%= link_to 'Back', styles_path %>

app/views/styles/index.html.erb
    <section class="colon14">

      <% @name="Hair Gallery" %>       
      


        <!-- START CONTENT AND SIDEBAR -->
        <div class="container general">
            <div id="content" class="single col-lg-12 col-md-12 col-sm-12">

                <div class="message text-center">
                    <h2>The most recent hairstyles on <span>Thomonique</span></h2>
                </div>
              
  <% @styles.each do |style| %>    
                <div class="col-lg-3 col-md-3 col-sm-6">
                	<div class="portfolio-columns">
                    <%= link_to(style,  "data-no-turbolink" => true) do %>                  
                          <%= cl_image_tag(style.image1,  :x => style.crop_x, :y => style.crop_y, :width => style.crop_w, :height => style.crop_h, :crop => :crop ) %>
                    <div>
                      <br><br>
                    <h5><%= style.name %></h5>
                    </div>
                    <%end %>
                   </div>
                </div>
    <% end %>            


        </div><!-- end container -->
         
         <div class="text-center">      
          <%= will_paginate @styles, renderer: BootstrapPagination::Rails %>  
				    <div class="clearfix"></div> 
          <%= link_to 'New Style', new_style_path, class:"btn btn-primary btn-lg text-center"%>
        </div>  	
    <!-- END CONTENT -->
    
	</section><!-- end colon1 -->

app/views/styles/new.html.erb
<% @name ="Post a Style" %>
<%= render 'form' %>

app/views/styles/show.html.erb
<% @name= @style.name %>
<section class="colon14">


        <!-- START CONTENT AND SIDEBAR -->
        <div class="container general">
            <div id="content" class="single-portfolio">
                
            	<div class="col-lg-6 col-md-6 col-sm-12">
                    <div id="myCarousel" class="carousel slide">
                      <div class="carousel-inner">
                        <!-- Slide 1 -->
                        <div class="item active">
                          <%= cl_image_tag(@style.image1,  :x => @style.crop_x, :y => @style.crop_y, :width => @style.crop_w, :height => @style.crop_h, :crop => :crop, :id => "zoom" ) %>
                        </div>
                        
                      </div>
                      
                    </div>  
                </div> 
                
            	<div class="col-lg-6 col-md-6 col-sm-12">
               	<h2 class="general-title">
                  <h2>
                     <%= @style.name %> <br>
                    <% if @style.stylist.nil? %>   
                            <small>Hair done by <%= @style.stylist_name %> </small>
                   <% elsif  !@style.stylist.nil? %>
                        <small>Hair done by <%= link_to @style.stylist.name, @style.stylist %> </small>
                  <% end %>
                  </h2>
                </h2>
                  <p>Posted by <%= link_to @style.user.name , @style.user %></p>
                    
                    <p><%= @style.description %></p>
                    
             
                <p>
                   <p>
                     <% if user_signed_in? && (current_user.voted_for? @style) %>
                        <%= link_to unlike_style_path(@style), method: :put do %>
                            <i class='fa fa-heart'></i>
                         <% end %>
                     <% else %>
                        <%= link_to like_style_path(@style), method: :put do %>
                            <i class='fa fa-heart-o'></i>
                        <% end %>
                    <% end %>
                    <%= @style.votes_for.size%> likes
                </p>
                <% if @style.user == current_user %>
                  <%= link_to "Edit", edit_style_path %>
                <% end %>
                <%= link_to "Back", styles_path %>
					<hr> 
                
                
                

                    <div class="clearfix"></div>
                
                  
                  <h4>Comments</h4>
                <div class="form-group">
                  <%= form_for Comment.new do |f|   %>
                      <%= f.text_area  :content, class:"form-control", placeholder:"Enter your comment here!", required: true%>
                      <% if user_signed_in? %>
                            <%= f.hidden_field :user_id, value: current_user.id %>
                      <%end %>
                      <%= f.hidden_field :style_id, value: @style.id %>
                    <br>
                      <%= f.submit "Submit this comment", class:"btn btn-primary" %>
                     
                    <% end %>
                </div>
               <div class="comments"> 
                 
                  <% @style.comments.order('created_at DESC').each do |com| %>
                    <ul class="dm-sidebar-nav">
                      <%= link_to image_tag(com.user.image.url(:thumbnail)), com.user %>
                      <li><%= com.content  %><br> <small><%= com.user.name %> on <%= com.created_at.strftime("%b, %Y") %></small></li>
                    </ul>
                  <% end %>
                </div>
              </div> 
            </div><!-- content -->
        </div><!-- end general -->
                
	</section><!-- end colon14 -->

app/views/styles/tag.html.erb
<% @name= "Tagging a Stylist" %>
 <section class="colon14">
        <!-- START CONTENT AND SIDEBAR -->
        <div class="container general">
            <div id="content" class="single col-lg-12 col-md-12 col-sm-12 text-center">
                <h2>Tag whoever did this hair</h2>
              
              
<%= form_for @style do |f| %>
<div class="row text-center">
  
      <div class="col-md-5">
            <div class="form-group">  
              <h3> Find them in this list </h3>
              <select name="stylist_id">
                  <option value=""><%= "Stylist not in this list" %></option>
                 <%= User.where(phone: :phone).each do |user| %>
                  <option value="<%= user.id %>" class="form-control"><%= user.name %></option>
                <% end %>
              </select>
          </div>
      </div>
<div class="col-md-2">
  <h1>OR</h1>
</div>
<div class="col-md-5">
          <div class="form-group">  
            <h3>Type their name here </h3>
            <%= f.text_field :stylist_id, class:'form-control', placeholder: 'Enter the name of the hair stylist', required: true %>  
          </div>
</div>
  
</div>
              <br>
            <p class="text-center"><%= f.submit "Tag the Stylist", class:"btn btn-primary btn-lg"%>

              </p>
              <% end %>
              
              
                 </div>  	
    <!-- END CONTENT -->
      </div>
	</section><!-- end colon1 -->


<script type="text/javascript">