config/routes.rb
Rails.application.routes.draw do
  

  resources :sites

  get 'galleries/top'
  get 'galleries/random'
  get 'stylists/top'
  get 'stylists/random'

  resources :comments

  devise_for :users
  
  resources :users do
    resources :activities
    member do
      put "follow", to: "users#follow"
      put "unfollow", to: "users#unfollow"
      get "feed", to: "users#feed"
      get "interaction", to: "users#interaction"
    end
  end
   
  resources :styles do
    resources :comments
    member do
      put "like", to: "styles#vote"
      put "unlike", to: "styles#unvote"
    end
  end
  

  get 'pages/about'
  get 'pages/weekly'
  get 'pages/monthly'
  get 'pages/contact'
  get 'pages/show'
  get 'pages/gallery'
  get 'pages/form'
  get 'pages/contest'
  
  root 'pages#home'

end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  caches_page :show 
  
  respond_to :html
  
  layout 'customsite' 

  def index
    @sites = Site.all
    respond_with(@sites)
  end

  def show
    respond_with(@site)
  end

  def new
    @site = Site.new
    respond_with(@site)
  end

  def edit
  end

  def create
    @site = Site.new(site_params)
    @site.save
    respond_with(@site)
  end

  def update
    @site.update(site_params)
    respond_with(@site)
  end

  def destroy
    @site.destroy
    respond_with(@site)
  end

  private
    def set_site
      @site = Site.find(params[:id])
    end

    def site_params
      params.require(:site).permit(:title, :subtitle, :domain, :subdomain, :level, :address, :city, :state, :zip, :phone, :headercarousel, :welcomemessage, :services, :reviews, :reservations, :styles, :backgroundcolor, :textcolor, :hightlightcolor)
    end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :domain %><br>
    <%= f.text_field :domain %>
  </div>
  <div class="field">
    <%= f.label :subdomain %><br>
    <%= f.text_field :subdomain %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :headercarousel %><br>
    <%= f.number_field :headercarousel %>
  </div>
  <div class="field">
    <%= f.label :welcomemessage %><br>
    <%= f.text_field :welcomemessage %>
  </div>
  <div class="field">
    <%= f.label :services %><br>
    <%= f.number_field :services %>
  </div>
  <div class="field">
    <%= f.label :reviews %><br>
    <%= f.number_field :reviews %>
  </div>
  <div class="field">
    <%= f.label :reservations %><br>
    <%= f.number_field :reservations %>
  </div>
  <div class="field">
    <%= f.label :styles %><br>
    <%= f.number_field :styles %>
  </div>
  <div class="field">
    <%= f.label :backgroundcolor %><br>
    <%= f.text_field :backgroundcolor %>
  </div>
  <div class="field">
    <%= f.label :textcolor %><br>
    <%= f.text_field :textcolor %>
  </div>
  <div class="field">
    <%= f.label :hightlightcolor %><br>
    <%= f.text_field :hightlightcolor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<h1>Listing sites</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Domain</th>
      <th>Subdomain</th>
      <th>Level</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Phone</th>
      <th>Headercarousel</th>
      <th>Welcomemessage</th>
      <th>Services</th>
      <th>Reviews</th>
      <th>Reservations</th>
      <th>Styles</th>
      <th>Backgroundcolor</th>
      <th>Textcolor</th>
      <th>Hightlightcolor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= site.title %></td>
        <td><%= site.subtitle %></td>
        <td><%= site.domain %></td>
        <td><%= site.subdomain %></td>
        <td><%= site.level %></td>
        <td><%= site.address %></td>
        <td><%= site.city %></td>
        <td><%= site.state %></td>
        <td><%= site.zip %></td>
        <td><%= site.phone %></td>
        <td><%= site.headercarousel %></td>
        <td><%= site.welcomemessage %></td>
        <td><%= site.services %></td>
        <td><%= site.reviews %></td>
        <td><%= site.reservations %></td>
        <td><%= site.styles %></td>
        <td><%= site.backgroundcolor %></td>
        <td><%= site.textcolor %></td>
        <td><%= site.hightlightcolor %></td>
        <td><%= link_to 'Show', site %></td>
        <td><%= link_to 'Edit', edit_site_path(site) %></td>
        <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site', new_site_path %>

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
  <!-- /. Header Start ./-->
  <%= render "layouts/zheader" %>
  <!-- /. Header End ./--> 
  
  <!-- /.Slider Start ./-->
  <%= render "layouts/zslider" %>
  
  <!-- /.Slider End ./--> 
  <!-- /. Welcome Start ./-->
  <section>
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12">
          <div class="welcome">
            <h2 class="main-title">Welcome To Our Spa Clinic</h2>
            <p class="welcome-txt">bob </p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- /. Welcome end ./-->
  
  <div class="mtop1"></div>
  
  <!-- /. Services Start ./-->
  <%= render "layouts/zservices" %>
  <!-- /. Services End ./-->   
  
  <!-- /. Quotes Start ./-->
  
  <%= render "layouts/zquotes" %>  
  <!-- /. Quotes End ./--> 
  
  <!-- /. Products start ./-->
  <div class="gap"></div>
  <%= render "layouts/zgallery" %>
  <div class="gap-50"></div>
  
  <!-- /. Footer Start ./-->
  <%= render "layouts/zfooter" %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @site.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @site.subtitle %>
</p>

<p>
  <strong>Domain:</strong>
  <%= @site.domain %>
</p>

<p>
  <strong>Subdomain:</strong>
  <%= @site.subdomain %>
</p>

<p>
  <strong>Level:</strong>
  <%= @site.level %>
</p>

<p>
  <strong>Address:</strong>
  <%= @site.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @site.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @site.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @site.zip %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @site.phone %>
</p>

<p>
  <strong>Headercarousel:</strong>
  <%= @site.headercarousel %>
</p>

<p>
  <strong>Welcomemessage:</strong>
  <%= @site.welcomemessage %>
</p>

<p>
  <strong>Services:</strong>
  <%= @site.services %>
</p>

<p>
  <strong>Reviews:</strong>
  <%= @site.reviews %>
</p>

<p>
  <strong>Reservations:</strong>
  <%= @site.reservations %>
</p>

<p>
  <strong>Styles:</strong>
  <%= @site.styles %>
</p>

<p>
  <strong>Backgroundcolor:</strong>
  <%= @site.backgroundcolor %>
</p>

<p>
  <strong>Textcolor:</strong>
  <%= @site.textcolor %>
</p>

<p>
  <strong>Hightlightcolor:</strong>
  <%= @site.hightlightcolor %>
</p>

<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>