config/routes.rb
Rails.application.routes.draw do
  

  resources :sites

  get 'galleries/top'
  get 'galleries/random'
  get 'stylists/top'
  get 'stylists/random'

  resources :comments

  devise_for :users
  
  resources :users do
    resources :activities
    member do
      put "follow", to: "users#follow"
      put "unfollow", to: "users#unfollow"
      get "feed", to: "users#feed"
      get "interaction", to: "users#interaction"
    end
  end
   
  resources :styles do
    resources :comments
    member do
      put "like", to: "styles#vote"
      put "unlike", to: "styles#unvote"
    end
  end
  

  get 'pages/about'
  get 'pages/weekly'
  get 'pages/monthly'
  get 'pages/contact'
  get 'pages/show'
  get 'pages/gallery'
  get 'pages/form'
  get 'pages/contest'
  
  root 'pages#home'

end

app/views/layouts/_footer.html.erb
	<footer class="footer-wrapper">
    	<div class="container">
        	<div class="col-lg-6 col-md-6 col-sm-6">
            	<div class="widget">
					<h2 class="general-title">
						<span>About Thomonique</span>
					</h2>
                    <p>Thomonique is a an online hair show displaying all the beatiful hair done in your neighborhood and around the world. Join our community by liking your favorite styles and sharing your opinions about them. </p> 
                <p>If you are a hair stylist, post pictures of your works here to see what others think.</p>
                <%= link_to "read more", pages_about_path, class:"btn btn-primary btn-sm" %>
				</div>
            </div>

        	<div class="col-lg-6 col-md-6 col-sm-6">
            	<div class="widget">
					<h2 class="general-title">
						<span>Contact Details</span>
					</h2>
                    <p>Feel free to contact us for feedback, inquiries, and business opportunities.</p>
                    	<ul class="contact-details">
                      	<li><i class="icon-home"></i>We are based in Washington, DC</li>
                        	<li><i class="icon-mobile-phone"></i> +0 554 777 78 78</li>
                         <li><i class="icon-envelope-alt"></i>thomonique@email.com</li>
                      </ul>
				</div>
            </div>
		</div>
	</footer>
    
	<div class="copyright-wrapper">
    	<div class="container">
        	<div class="col-lg-6 col-md-6 col-sm-6">
            	<span class="copyright">
                    © Copyright 2015 -
                    <a href="#">Thomonique</a>
                </span>
            </div>
        	<div class="col-lg-6 col-md-6 col-sm-6">
                <nav>
                    <ul class="footer-menu">
                  		<li><a href="/" ><i class="icon-home"></i> Home</a>
                  		<li><%= link_to "Gallery", styles_path %></li>
                  		<li><%= link_to "About", pages_about_path %></li>
                  		<li><%= link_to "Contact", pages_contact_path %></li>
                    </ul>
                </nav>
            </div>
		</div>
	</div>

<div class="dmtop">Scroll to Top</div>

app/views/layouts/_header.html.erb
<div class="topbar">
            <div class="container">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <p class="tagline">Call us : +90 532 02 02 // Email us : hello@designingmedia.com</p>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <ul class="dm-social">
                        <li><a href="#" data-toggle="tooltip" data-placement="bottom" class="icon-facebook" title="Facebook">Facebook</a></li>
                        <li><a href="#" data-toggle="tooltip" data-placement="bottom" class="icon-google-plus" title="Google+">Google+</a></li>
                        <li><a href="#" data-toggle="tooltip" data-placement="bottom" class="icon-twitter" title="Twitter">Twitter</a></li>
                        <li><a href="#" data-toggle="tooltip" data-placement="bottom" class="icon-pinterest" title="Pinterest">Pinterest</a></li>
                        <li><a href="#" data-toggle="tooltip" data-placement="bottom" class="icon-linkedin" title="Linkedin">Linkedin</a></li>
                        <li><a href="#" data-toggle="tooltip" data-placement="bottom" class="icon-rss" title="Feedburner">RSS</a></li>
                    </ul><!-- End Social --> 
                </div>
            </div>
        </div><!-- /topbar -->

      <header class="header-wrapper">
		<div class="container">
            	<div class="col-lg-2 col-md-2 col-sm-2">
                   <a class="navbar-brand" href="/"><i class="fa fa-scissors"></i> Thomonique</a>
                </div>
            	<div class="col-lg-10 col-md-10 col-sm-12">
                          <nav class="navbar navbar-default fhmm" role="navigation">
                        <div class="navbar-header">
                            <button type="button" data-toggle="collapse" data-target="#defaultmenu" class="navbar-toggle"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                        </div><!-- end navbar-header -->
                        <div id="defaultmenu" class="navbar-collapse collapse container">
                            <ul class="nav navbar-nav">
                                <li><a href="/" ><i class="icon-home"></i> Home</a>
                                </li><!-- end standard drop down -->
                                <li><%= link_to "Hair Gallery", styles_path %></li>
                                 
 
                               <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Styles <b class="caret"></b></a>
                                    <ul class="dropdown-menu" role="menu">
                                      <li><%= link_to "Top Hairstyles", galleries_top_path %></li>
                                      <li><%= link_to "Random Hairstyles", galleries_random_path %></li>
                                       
                                    </ul><!-- end dropdown-menu -->
                                </li><!-- end standard drop down -->   
                              
                                 <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Contests <b class="caret"></b></a>
                                    <ul class="dropdown-menu" role="menu">
                                       <li><%= link_to "Daily Contests", pages_contest_path %></li>
                                      <li><%= link_to "Weekly Contests", pages_weekly_path %></li>
                                       <li><%= link_to "Monthly Contests", pages_monthly_path %></li>
                                    </ul><!-- end dropdown-menu -->
                                </li><!-- end standard drop down -->   
                             
                                <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">About <b class="caret"></b></a>
                                    <ul class="dropdown-menu" role="menu">
                                      <li><%= link_to "About Thomonique", pages_about_path %></li>
                                        <li><%= link_to "Contact Us", pages_contact_path %></li>
                                   
                                    </ul><!-- end dropdown-menu -->
                                </li><!-- end standard drop down -->  
                                                                            
                            </ul><!-- end nav navbar-nav -->
                            <ul class="nav navbar-nav navbar-right">
                                <% if user_signed_in? %>
                                  <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Logged in as <%= current_user.name %> <span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                      <li><%= link_to "View Profile", current_user  %></li>
                                      <li><%= link_to "Edit Profile", edit_user_registration_path  %></li>
                                      <li><%= link_to "Add a Style", new_style_path  %></li>
                                      <li><%= link_to "Log Out", destroy_user_session_path, method: :delete  %></li>
                                    </ul>
                                  </li>
                                <% else %>
                                  <li><%= link_to "Sign up", new_user_registration_path  %></li>
                                  <li><%= link_to "Log in", new_user_session_path  %></li>
                                <% end %>
                              
                            </ul><!-- end nav navbar-nav navbar-right -->
                        </div><!-- end #navbar-collapse-1 -->
					</nav><!-- end navbar navbar-default fhmm -->
			</div><!-- /col10 -->
		</div><!-- /container -->
    </header><!-- /header wrapper -->

app/views/layouts/_js.html.erb
<script>
 "use strict";
 	$('.dropdown-toggle').dropdownHover().dropdown();

// Tooltips
    $("[data-toggle=tooltip]").tooltip();

    $("[data-toggle=popover]")
      .popover()

// Menu drop down effect
		$('.dropdown-toggle').dropdownHover().dropdown();
		$(document).on('click', '.fhmm .dropdown-menu', function(e) {
		  e.stopPropagation()
		})
		  
// Count Script
	function count($this){
		var current = parseInt($this.html(), 10);
		current = current + 1; /* Where 50 is increment */
	
		$this.html(++current);
		if(current > $this.data('count')){
			$this.html($this.data('count'));
		} else {    
			setTimeout(function(){count($this)}, 50);
		}
	}        
	
	$(".stat-count").each(function() {
	  $(this).data('count', parseInt($(this).html(), 10));
	  $(this).html('0');
	  count($(this));
	});

// Accordion Toggle Items
   var iconOpen = 'icon-minus',
        iconClose = 'icon-plus';

    $(document).on('show.bs.collapse hide.bs.collapse', '.accordion', function (e) {
        var $target = $(e.target)
          $target.siblings('.accordion-heading')
          .find('em').toggleClass(iconOpen + ' ' + iconClose);
          if(e.type == 'show')
              $target.prev('.accordion-heading').find('.accordion-toggle').addClass('active');
          if(e.type == 'hide')
              $(this).find('.accordion-toggle').not($target).removeClass('active');
    });

// Tooltip
	$('.dm-social, .client, .buddy-members').tooltip({
		selector: "a[data-toggle=tooltip]"
	})
	
	$('.dm-social, .client, .buddy-members').tooltip()

// Back to Top
 jQuery(window).scroll(function(){
	if (jQuery(this).scrollTop() > 1) {
			jQuery('.dmtop').css({bottom:"25px"});
		} else {
			jQuery('.dmtop').css({bottom:"-100px"});
		}
	});
	jQuery('.dmtop').click(function(){
		jQuery('html, body').animate({scrollTop: '0px'}, 800);
		return false;
});




</script>

app/views/layouts/_reservation.html.erb
    <section class="ftop">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <form  method="post">
              <ul class="reservation">
                <li>
                  <h3>Reservations</h3>
                </li>
                <li>
                  <label>Arrival Date</label>
                  <input name="date" type="text" size="10" id="datepicker" placeholder="10/01/2014">
                  <span><i class="fa fa-calendar"></i></span> </li>
                <li>
                  <label>Departure Date</label>
                  <input name="ddate" type="text" value="" size="10" id="datepicker2" placeholder="20/01/2014">
                  <span><i class="fa fa-calendar"></i></span> </li>
                <li>
                  <label>Time</label>
                  <input id="duration" type="text" size="8" class="time" placeholder="Time">
                  <span><i class="fa fa-clock-o"></i></span> </li>
                <li>
                  <label>Adults</label>
                  <select name="adults" class="adults">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                  </select>
                </li>
                <li> <a href="reservation.html">Reserve</a> </li>
              </ul>
            </form>
          </div>
        </div>
      </div>
    </section>
    

app/views/layouts/_zfooter.html.erb
  <section id="footer">

    <!-- /. Footer Bottom Bar ./-->
    
    <section class="footer-mid">
      <div class="footer-midbg">
        <div class="container">
          <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12  flickr">
              <h3>Flickr Photos</h3>
              <ul class="lb-album">
                <li> <a href="#image-1"> <%= image_tag "fp1.jpg" %><span></span> </a>
                  <div class="lb-overlay" id="image-1"> <%= image_tag "large1.gif" %>
                    <div>
                      <p>Image Tagline Will Come here</p>
                    </div>
                    <a href="#page" class="lb-close"><i class="fa fa-times-circle"></i></a> </div>
                </li>
                <li> <a href="#image-2"> <%= image_tag "fp2.jpg"  %> <span></span> </a>
                  <div class="lb-overlay" id="image-2"> <%= image_tag "large1.gif" %>
                    <div>
                      <p>Image Tagline Will Come here</p>
                    </div>
                    <a href="#page" class="lb-close"><i class="fa fa-times-circle"></i></a> </div>
                </li>
                <li> <a href="#image-3"> <%= image_tag "fp3.jpg" %> <span></span> </a>
                  <div class="lb-overlay" id="image-3"> <%= image_tag "large1.gif" %>
                    <div>
                      <p>Image Tagline Will Come here</p>
                    </div>
                    <a href="#page" class="lb-close"><i class="fa fa-times-circle"></i></a> </div>
                </li>
                <li> <a href="#image-4"> <%= image_tag "fp4.jpg" %> <span></span> </a>
                  <div class="lb-overlay" id="image-4"> <%= image_tag "large1.gif" %>
                    <div>
                      <p>Image Tagline Will Come here</p>
                    </div>
                    <a href="#page" class="lb-close"><i class="fa fa-times-circle"></i></a> </div>
                </li>
                <li> <a href="#image-5"> <%= image_tag "fp5.jpg" %> <span></span> </a>
                  <div class="lb-overlay" id="image-5"> <%= image_tag "large1.gif" %>
                    <div>
                      <p>Image Tagline Will Come here</p>
                    </div>
                    <a href="#page" class="lb-close"><i class="fa fa-times-circle"></i></a> </div>
                </li>
                <li> <a href="#image-6"> <%= image_tag "fp1.jpg" %> <span></span> </a>
                  <div class="lb-overlay" id="image-6"> <%= image_tag "large1.gif" %>
                    <div>
                      <p>Image Tagline Will Come here</p>
                    </div>
                    <a href="#page" class="lb-close"><i class="fa fa-times-circle"></i></a> </div>
                </li>
                <li> <a href="#image-7"> <%= image_tag "fp7.jpg" %> <span></span> </a>
                  <div class="lb-overlay" id="image-7"> <%= image_tag "large1.gif" %>
                    <div>
                      <p>Image Tagline Will Come here</p>
                    </div>
                    <a href="#page" class="lb-close"><i class="fa fa-times-circle"></i></a> </div>
                </li>
                <li> <a href="#image-8"> <%= image_tag "fp8.jpg" %> <span></span> </a>
                  <div class="lb-overlay" id="image-8"> <%= image_tag "large1.gif" %>
                    <div>
                      <p>Image Tagline Will Come here</p>
                    </div>
                    <a href="#page" class="lb-close"><i class="fa fa-times-circle"></i></a> </div>
                </li>
                <li> <a href="#image-9"> <%= image_tag "fp9.jpg" %> <span></span> </a>
                  <div class="lb-overlay" id="image-9"> <%= image_tag "large1.gif" %>
                    <div>
                      <p>Image Tagline Will Come here</p>
                    </div>
                    <a href="#page" class="lb-close"><i class="fa fa-times-circle"></i></a> </div>
                </li>
              </ul>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 fposts">
              <h3>Recent Posts</h3>
              <ul class="recent-posts">
                <li><a href="blog-details.html">Bed ut perspiciatis unde omnis</a></li>
                <li><a href="blog-details.html">Duis aute irure dolor in excepteur</a></li>
                <li><a href="blog-details.html">Sint occaecat cupidatat nemo enim</a></li>
                <li><a href="blog-details.html">Voluptatem quia autem vel eum iure</a></li>
                <li><a href="blog-details.html">Bed ut perspiciatis unde omnis</a></li>
                <li><a href="blog-details.html">Duis aute irure dolor in excepteur</a></li>
                <li><a href="blog-details.html">Sint occaecat cupidatat nemo enim</a></li>
              </ul>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 feeds">
              <h3>Tweets</h3>
              <div>
                <ul class="tweets">
                  <li class="twuser"><%= image_tag "twuser-1.jpg" %></li>
                  <li class="twpost">
                    <h4><a href="#">@johndoe</a></h4>
                    <p> There are many variations of passages the majority. <span class="url"><a href="#">themeforest.net/item/boxme-res</a></span> </p>
                  </li>
                </ul>
                <ul class="tweets">
                  <li class="twuser"><%= image_tag "twuser-2.jpg" %></li>
                  <li class="twpost">
                    <h4><a href="#">@dazy</a></h4>
                    <p> There are many variations of passages the majority. <span class="url"><a href="#">themeforest.net/item/boxme-res</a></span> </p>
                  </li>
                </ul>
                <ul class="tweets">
                  <li class="twuser"><%= image_tag "twuser-3.jpg" %></li>
                  <li class="twpost">
                    <h4><a href="#">@lizaanderson</a></h4>
                    <p> There are many variations of passages the majority. <span class="url"><a href="#">themeforest.net/item/boxme-res</a></span> </p>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 getintouch">
              <h3>Get in Touch</h3>
              <p> when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries. </p>
              <p>Phone: (012) 123 456<br>
                Fax: (012) 123 456<br>
                Email: <a href="mailto:info@relaxspapalace.com">info@relaxspapalace.com</a><br>
                <a href="#">www.relaxspapalace.com</a> </p>
              <div class="social"> <a href="#" title="Facebook"><i class="fa fa-facebook-square"></i></a> <a href="#" title="Linkedin"><i class="fa fa-linkedin-square"></i></a> <a href="#" title="Gplus"><i class="fa fa-google-plus-square"></i></a> <a href="#" title="Twitter"><i class="fa fa-twitter-square"></i></a> <a href="#" title="Pinterest"><i class="fa fa-pinterest-square"></i></a> <a href="#" title="Instagram"><i class="fa fa-instagram"></i></a> <a href="#" title="Flickr"><i class="fa fa-flickr"></i></a> </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    
    <!-- /. Footer Copy rights ./-->
    
    <section class="footer-copy">
      <div class="container">
        <div class="row">
          <div class="col-lg-12"><strong>Pageant Beauty Palace</strong> &copy; 2014 All Rights Reserved, Designed &amp; Developed by: <a href="http://CrunchPress.com" title="Crunch Press" target="_blank">CrunchPress.com</a></div>
        </div>
      </div>
    </section>
  </section>
  <!-- /. Footer End ./--> 

app/views/layouts/_zgallery.html.erb
  <section class="home-products gallery">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12">
          <h2 class="main-title">Examples of My Work</h2>
          <h4 class="sub-title">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.</h4>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-6 cp_load fadeInUp">
          <ul class="pro-box">
            <li class="pro">
              <div class="block-image"> <%= image_tag "hpro1.jpg", :class => "img-responsive" %>
                <div class="img-overlay-3-up pat-override"></div>
                <div class="img-overlay-3-down pat-override"></div>
                <ol class="static-style">
                  <li class="white-rounded"><a href="product-details.html"><i class="fa fa-link"></i></a> </li>
                  <li class="white-rounded"><a href="images/large/large1.gif" data-rel="prettyPhoto[gallery1]" ><i class="fa fa-plus"></i></a> </li>
                </ol>
              </div>
              <span class="addtocart"><a href="cart.html">Add To Cart</a></span> </li>
            <li>
              <h4><a href="product-details.html">Massage Equipments</a></h4>
            </li>
            <li>We have many equipments of massage</li>
            <li class="pro-footer"><span class="price">$199.00</span> <span class="rating"> <a href="#"><i class="fa fa-star"></i></a> <a href="#"><i class="fa fa-star"></i></a> <a href="#"><i class="fa fa-star-o"></i></a> <a href="#"> <i class="fa fa-star-o"></i></a> <a href="#"> <i class="fa fa-star-o"></i></a> </span> </li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 cp_load fadeInUp">
          <ul class="pro-box">
            <li class="pro">
              <div class="block-image"> <%= image_tag "hpro2.jpg", :class => "img-responsive" %>
                <div class="img-overlay-3-up pat-override"></div>
                <div class="img-overlay-3-down pat-override"></div>
                <ol class="static-style">
                  <li class="white-rounded"><a href="product-details.html"><i class="fa fa-link"></i></a> </li>
                  <li class="white-rounded"><a href="images/large/large1.gif" data-rel="prettyPhoto[gallery1]" ><i class="fa fa-plus"></i></a> </li>
                </ol>
              </div>
              <span class="addtocart"><a href="cart.html">Add To Cart</a></span> </li>
            <li>
              <h4><a href="product-details.html">Massage Equipments</a></h4>
            </li>
            <li>We have many equipments of massage</li>
            <li class="pro-footer"><span class="price">$199.00</span> <span class="rating"> <a href="#"><i class="fa fa-star"></i></a> <a href="#"><i class="fa fa-star"></i></a> <a href="#"><i class="fa fa-star-o"></i></a> <a href="#"> <i class="fa fa-star-o"></i></a> <a href="#"> <i class="fa fa-star-o"></i></a> </span> </li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 cp_load fadeInUp">
          <ul class="pro-box">
            <li class="pro">
              <div class="block-image"> <%= image_tag "hpro3.jpg", :class => "img-responsive" %>
                <div class="img-overlay-3-up pat-override"></div>
                <div class="img-overlay-3-down pat-override"></div>
                <ol class="static-style">
                  <li class="white-rounded"><a href="product-details.html"><i class="fa fa-link"></i></a> </li>
                  <li class="white-rounded"><a href="images/large/large1.gif" data-rel="prettyPhoto[gallery1]" ><i class="fa fa-plus"></i></a> </li>
                </ol>
              </div>
              <span class="addtocart"><a href="cart.html">Add To Cart</a></span> </li>
            <li>
              <h4><a href="product-details.html">Massage Equipments</a></h4>
            </li>
            <li>We have many equipments of massage</li>
            <li class="pro-footer"><span class="price">$199.00</span> <span class="rating"> <a href="#"><i class="fa fa-star"></i></a> <a href="#"><i class="fa fa-star"></i></a> <a href="#"><i class="fa fa-star-o"></i></a> <a href="#"> <i class="fa fa-star-o"></i></a> <a href="#"> <i class="fa fa-star-o"></i></a> </span> </li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 cp_load fadeInUp">
          <ul class="pro-box">
            <li class="pro">
              <div class="block-image"> <%= image_tag "hpro4.jpg", :class => "img-responsive" %>
                <div class="img-overlay-3-up pat-override"></div>
                <div class="img-overlay-3-down pat-override"></div>
                <ol class="static-style">
                  <li class="white-rounded"><a href="product-details.html"><i class="fa fa-link"></i></a> </li>
                  <li class="white-rounded"><a href="images/large/large1.gif" data-rel="prettyPhoto[gallery1]" ><i class="fa fa-plus"></i></a> </li>
                </ol>
              </div>
              <span class="addtocart"><a href="cart.html">Add To Cart</a></span> </li>
            <li>
              <h4><a href="product-details.html">Massage Equipments</a></h4>
            </li>
            <li>We have many equipments of massage</li>
            <li class="pro-footer"><span class="price">$199.00</span> <span class="rating"> <a href="#"><i class="fa fa-star"></i></a> <a href="#"><i class="fa fa-star"></i></a> <a href="#"><i class="fa fa-star-o"></i></a> <a href="#"> <i class="fa fa-star-o"></i></a> <a href="#"> <i class="fa fa-star-o"></i></a> </span></li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  <!-- /. Products End ./-->

app/views/layouts/_zheader.html.erb
<header id="header">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-3">
          <div class="logo"><a href="index.html"><strong class="logo-home"> Relax Spa</strong></a></div>
        </div>
        <div class="col-lg-9 col-md-9"> 
          <!-- Collect the nav links, forms, and other content for toggling --> 
          
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="home-menu">
            <div class="navbar mm">
              <div>
                <nav class="navbar navbar-default" role="navigation"> 
                  <!-- Brand and toggle get grouped for better mobile display -->
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                  </div>
                  <div id="navbar-collapse-1" class="collapse navbar-collapse pull-right">
                    <ul class="nav navbar-nav">
                      <li><a href="index.html">Home</a></li>
                      <li><a href="prices.html">Prices</a></li>
                      <li><a href="gallery.html">Gallery</a></li>
                      <li><a href="contact.html">Contact</a></li>
                      

                      
                    </ul>
                  </div>
                </nav>
              </div>
            </div>
          </div>
          <!-- /.navbar-collapse --> 
        </div>
      </div>
    </div>
  </header>

app/views/layouts/_zquotes.html.erb
  <section class="quote-bg">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <ul class="quote-slider">
            <li> <i class="fa fa-quote-left"></i>
              <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
              <%= image_tag "quote-user.jpg" %>
              <h4>Eliza Jonsep</h4>
            </li>
            <li> <i class="fa fa-quote-left"></i>
              <p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
              <%= image_tag "buser1.jpg" %>
              <h4>Jonsep Eliza</h4>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thomonique</title>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

  <%= stylesheet_link_tag    'application', params[:controller], media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <%= render "layouts/header" %>
  <%= render "layouts/display" %>
  <div class="container">
    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash#{name}" %>
    <% end %>
    <%= yield %>
  </div> 
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= render "layouts/footer" %>
  <%= render "layouts/js" %> 
  
  
</body>
</html>